# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'v1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtCore
import sys
import flask_app


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(780, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AccidentTable = QtWidgets.QTableWidget(self.centralwidget)
        self.AccidentTable.setGeometry(QtCore.QRect(10, 90, 761, 311))
        self.AccidentTable.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.AdjustIgnored
        )
        self.AccidentTable.setObjectName("AccidentTable")
        self.AccidentTable.setColumnCount(6)
        self.AccidentTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.AccidentTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.AccidentTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.AccidentTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.AccidentTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.AccidentTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.AccidentTable.setHorizontalHeaderItem(5, item)
        self.AccidentTable.horizontalHeader().setVisible(True)
        self.AccidentTable.horizontalHeader().setDefaultSectionSize(125)
        self.EVTable = QtWidgets.QTableWidget(self.centralwidget)
        self.EVTable.setEnabled(True)
        self.EVTable.setGeometry(QtCore.QRect(10, 440, 761, 181))
        self.EVTable.setObjectName("EVTable")
        self.EVTable.setColumnCount(4)
        self.EVTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.EVTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.EVTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.EVTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.EVTable.setHorizontalHeaderItem(3, item)
        self.SystemName = QtWidgets.QLabel(self.centralwidget)
        self.SystemName.setGeometry(QtCore.QRect(320, 10, 131, 41))
        self.SystemName.setObjectName("SystemName")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 70, 81, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 420, 121, 21))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 788, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.AccidentTable.setColumnWidth(0, 59)
        self.AccidentTable.setColumnWidth(1, 80)
        self.AccidentTable.setColumnWidth(2, 300)
        self.AccidentTable.setColumnWidth(3, 100)
        self.AccidentTable.setColumnWidth(4, 120)
        self.AccidentTable.setColumnWidth(5, 100)

        self.EVTable.setColumnWidth(0, 59)
        self.EVTable.setColumnWidth(1, 80)
        self.EVTable.setColumnWidth(2, 300)
        self.EVTable.setColumnWidth(3, 200)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.AccidentTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "No"))
        item = self.AccidentTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Code"))
        item = self.AccidentTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Location"))
        item = self.AccidentTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Time"))
        item = self.AccidentTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Severity"))
        item = self.AccidentTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Image"))
        item = self.EVTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "No"))
        item = self.EVTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Code"))
        item = self.EVTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "E.V. Allocated"))
        item = self.EVTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "E.V. Time of Arrival"))
        self.SystemName.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center"><span style=" font-size:16pt; font-weight:600;">SELAMAT</span></p></body></html>',
            )
        )
        self.label.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style=" font-size:9pt;">Accident</span></p></body></html>',
            )
        )
        self.label_2.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style=" font-size:9pt;">Emergency Vehicle</span></p></body></html>',
            )
        )


def run_qt_app():
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()

    def update_ui():
        # Implement your UI update logic here
        data_dict = flask_app.fetch_data()
        data_accident = data_dict.get("data_accident", {})
        data_ev = data_dict.get("data_ev", {})
        flask_app.populate_data(data_accident, data_ev, ui)

    # Create a timer to periodically update the UI
    timer = QtCore.QTimer()
    timer.timeout.connect(update_ui)
    timer.start(500)  # Set the interval in milliseconds (e.g., 5000 ms = 5 seconds)

    # Initial UI update
    update_ui()

    sys.exit(app.exec_())


if __name__ == "__main__":
    run_qt_app()
